language: go
go:
  - "1.16.5"
os: linux
virt: lxd
group: edge
arch: arm64-graviton2
notifications:
  email:
    recipients:
      - raghu@getfastah.com
      - siddharth@getfastah.com
    on_success: change # default: change
    on_failure: always # default: always
